# coding: utf-8

"""
    Modelstore

    Machine Learning model store api   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: noonefornow@nowhere.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.model_api import ModelApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.model_api.ModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_model(self):
        """Test case for add_model

        Add a new model  # noqa: E501
        """
        pass

    def test_delete_model_by_id(self):
        """Test case for delete_model_by_id

        Deletes a model by Id  # noqa: E501
        """
        pass

    def test_delete_model_by_name(self):
        """Test case for delete_model_by_name

        Deletes a model by name  # noqa: E501
        """
        pass

    def test_find_models_by_status(self):
        """Test case for find_models_by_status

        Finds Model by status  # noqa: E501
        """
        pass

    def test_find_models_by_tags(self):
        """Test case for find_models_by_tags

        Finds Models by tags  # noqa: E501
        """
        pass

    def test_get_model_by_id(self):
        """Test case for get_model_by_id

        Find model by ID  # noqa: E501
        """
        pass

    def test_get_model_by_name(self):
        """Test case for get_model_by_name

        Find model by Name  # noqa: E501
        """
        pass

    def test_update_model(self):
        """Test case for update_model

        Update an existing model  # noqa: E501
        """
        pass

    def test_update_model_with_form(self):
        """Test case for update_model_with_form

        Updates a model in the store with form data  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        uploads the model data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
